pipeline {
    agent {
        label 'Agent-1'
    }
    environment {
        EC2_IP ="Need to gieve EC2 IP here"
        environment = "dev"
        brand = "Mcom"
    }
    stages {
        stage('Build') {
            steps {
                sh 'echo Building...'
            }
        }
        stage('Test') {
            steps {
                sh 'echo Testing...'
            }
        }
        stage('Deploy') {
            steps {
                sh 'echo Deploying...'
            }
        }
    }
    post {
        always {
            sh 'echo This always runs, regardless of the build result.'
        }
        success {
            sh 'echo Pipeline succeeded!'
            // Add notification (e.g., Slack, Email) here
        }
        failure {
            sh 'echo Pipeline failed!'
            // Add notification (e.g., Slack, Email) here
        }
    }
}